query deliveryProfiles($merchantOwnedOnly: Boolean, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean){
    deliveryProfiles(merchantOwnedOnly: $merchantOwnedOnly, first: $first, after: $after, last: $last, before: $before, reverse: $reverse){
        edges{
            cursor
        }
        nodes{
            activeMethodDefinitionsCount
            default
            id
            legacyMode
            locationsWithoutRatesCount
            name
            originLocationCount
            zoneCountryCount
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}