query dispute($id: ID!){
    dispute(id: $id){
        amount{
            amount
            currencyCode
        }
        evidenceDueBy
        evidenceSentOn
        finalizedOn
        id
        initiatedAt
        legacyResourceId
        order{
            billingAddressMatchesShippingAddress
            canMarkAsPaid
            canNotifyCustomer
            cancelReason
            cancelledAt
            capturable
            clientIp
            closed
            closedAt
            confirmationNumber
            confirmed
            createdAt
            currencyCode
            currentSubtotalLineItemsQuantity
            currentTotalWeight
            customerAcceptsMarketing
            customerLocale
            discountCode
            discountCodes
            displayFinancialStatus
            displayFulfillmentStatus
            edited
            email
            estimatedTaxes
            fulfillable
            fullyPaid
            hasTimelineComment
            id
            legacyResourceId
            merchantEditable
            merchantEditableErrors
            name
            note
            paymentGatewayNames
            phone
            poNumber
            presentmentCurrencyCode
            processedAt
            purchasingEntity{
                __typename
                ... on Customer {
                    canDelete
                    createdAt
                    dataSaleOptOut
                    displayName
                    email
                    firstName
                    hasTimelineComment
                    id
                    lastName
                    legacyResourceId
                    lifetimeDuration
                    locale
                    multipassIdentifier
                    note
                    numberOfOrders
                    phone
                    productSubscriberStatus
                    state
                    tags
                    taxExempt
                    taxExemptions
                    unsubscribeUrl
                    updatedAt
                    validEmailAddress
                    verifiedEmail
                }
            }
            refundable
            registeredSourceUrl
            requiresShipping
            restockable
            returnStatus
            sourceIdentifier
            sourceName
            subtotalLineItemsQuantity
            tags
            taxExempt
            taxesIncluded
            test
            totalWeight
            unpaid
            updatedAt
        }
        reasonDetails{
            networkReasonCode
            reason
        }
        status
        type
    }
}