query disputeEvidence($withName: Boolean, $withCompany: Boolean, $withName1: Boolean, $withCompany1: Boolean, $id: ID!){
    disputeEvidence(id: $id){
        accessActivityLog
        billingAddress{
            address1
            address2
            city
            company
            coordinatesValidated
            country
            countryCodeV2
            firstName
            formatted(withName: $withName, withCompany: $withCompany)
            formattedArea
            id
            lastName
            latitude
            longitude
            name
            phone
            province
            provinceCode
            timeZone
            validationResultSummary
            zip
        }
        cancellationPolicyDisclosure
        cancellationPolicyFile{
            disputeEvidenceType
            fileSize
            fileType
            id
            originalFileName
            url
        }
        cancellationRebuttal
        customerCommunicationFile{
            disputeEvidenceType
            fileSize
            fileType
            id
            originalFileName
            url
        }
        customerEmailAddress
        customerFirstName
        customerLastName
        customerPurchaseIp
        dispute{
            evidenceDueBy
            evidenceSentOn
            finalizedOn
            id
            initiatedAt
            legacyResourceId
            status
            type
        }
        disputeFileUploads{
            disputeEvidenceType
            fileSize
            fileType
            id
            originalFileName
            url
        }
        fulfillments{
            id
            shippingCarrier
            shippingDate
            shippingTrackingNumber
        }
        id
        productDescription
        refundPolicyDisclosure
        refundPolicyFile{
            disputeEvidenceType
            fileSize
            fileType
            id
            originalFileName
            url
        }
        refundRefusalExplanation
        serviceDocumentationFile{
            disputeEvidenceType
            fileSize
            fileType
            id
            originalFileName
            url
        }
        shippingAddress{
            address1
            address2
            city
            company
            coordinatesValidated
            country
            countryCodeV2
            firstName
            formatted(withName: $withName1, withCompany: $withCompany1)
            formattedArea
            id
            lastName
            latitude
            longitude
            name
            phone
            province
            provinceCode
            timeZone
            validationResultSummary
            zip
        }
        shippingDocumentationFile{
            disputeEvidenceType
            fileSize
            fileType
            id
            originalFileName
            url
        }
        submitted
        uncategorizedFile{
            disputeEvidenceType
            fileSize
            fileType
            id
            originalFileName
            url
        }
        uncategorizedText
    }
}