query draftOrders($first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $sortKey: DraftOrderSortKeys, $query: String, $savedSearchId: ID){
    draftOrders(first: $first, after: $after, last: $last, before: $before, reverse: $reverse, sortKey: $sortKey, query: $query, savedSearchId: $savedSearchId){
        edges{
            cursor
        }
        nodes{
            acceptAutomaticDiscounts
            allowDiscountCodesInCheckout
            billingAddressMatchesShippingAddress
            completedAt
            createdAt
            currencyCode
            defaultCursor
            discountCodes
            email
            hasTimelineComment
            id
            invoiceEmailTemplateSubject
            invoiceSentAt
            invoiceUrl
            legacyResourceId
            marketName
            marketRegionCountryCode
            name
            note2
            phone
            poNumber
            presentmentCurrencyCode
            purchasingEntity{
                __typename
                ... on Customer {
                    canDelete
                    createdAt
                    dataSaleOptOut
                    displayName
                    email
                    firstName
                    hasTimelineComment
                    id
                    lastName
                    legacyResourceId
                    lifetimeDuration
                    locale
                    multipassIdentifier
                    note
                    numberOfOrders
                    phone
                    productSubscriberStatus
                    state
                    tags
                    taxExempt
                    taxExemptions
                    unsubscribeUrl
                    updatedAt
                    validEmailAddress
                    verifiedEmail
                }
            }
            ready
            reserveInventoryUntil
            status
            tags
            taxExempt
            taxesIncluded
            totalQuantityOfLineItems
            totalWeight
            transformerFingerprint
            updatedAt
            visibleToCustomer
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}