query fulfillment($first: Int, $id: ID!){
    fulfillment(id: $id){
        createdAt
        deliveredAt
        displayStatus
        estimatedDeliveryAt
        id
        inTransitAt
        legacyResourceId
        location{
            activatable
            addressVerified
            createdAt
            deactivatable
            deactivatedAt
            deletable
            fulfillsOnlineOrders
            hasActiveInventory
            hasUnfulfilledOrders
            id
            isActive
            isFulfillmentService
            legacyResourceId
            name
            shipsInventory
            updatedAt
        }
        name
        order{
            billingAddressMatchesShippingAddress
            canMarkAsPaid
            canNotifyCustomer
            cancelReason
            cancelledAt
            capturable
            clientIp
            closed
            closedAt
            confirmationNumber
            confirmed
            createdAt
            currencyCode
            currentSubtotalLineItemsQuantity
            currentTotalWeight
            customerAcceptsMarketing
            customerLocale
            discountCode
            discountCodes
            displayFinancialStatus
            displayFulfillmentStatus
            edited
            email
            estimatedTaxes
            fulfillable
            fullyPaid
            hasTimelineComment
            id
            legacyResourceId
            merchantEditable
            merchantEditableErrors
            name
            note
            paymentGatewayNames
            phone
            poNumber
            presentmentCurrencyCode
            processedAt
            purchasingEntity{
                __typename
                ... on Customer {
                    canDelete
                    createdAt
                    dataSaleOptOut
                    displayName
                    email
                    firstName
                    hasTimelineComment
                    id
                    lastName
                    legacyResourceId
                    lifetimeDuration
                    locale
                    multipassIdentifier
                    note
                    numberOfOrders
                    phone
                    productSubscriberStatus
                    state
                    tags
                    taxExempt
                    taxExemptions
                    unsubscribeUrl
                    updatedAt
                    validEmailAddress
                    verifiedEmail
                }
            }
            refundable
            registeredSourceUrl
            requiresShipping
            restockable
            returnStatus
            sourceIdentifier
            sourceName
            subtotalLineItemsQuantity
            tags
            taxExempt
            taxesIncluded
            test
            totalWeight
            unpaid
            updatedAt
        }
        originAddress{
            address1
            address2
            city
            countryCode
            provinceCode
            zip
        }
        requiresShipping
        service{
            callbackUrl
            handle
            id
            inventoryManagement
            permitsSkuSharing
            serviceName
            trackingSupport
            type
        }
        status
        totalQuantity
        trackingInfo(first: $first){
            company
            number
            url
        }
        updatedAt
    }
}