query menu($limit: Int, $locale: String!, $marketId: ID, $id: ID!){
    menu(id: $id){
        handle
        id
        isDefault
        items(limit: $limit){
            id
            resourceId
            tags
            title
            type
            url
        }
        title
        translations(locale: $locale, marketId: $marketId){
            key
            locale
            outdated
            updatedAt
            value
        }
    }
}