query metaobjectDefinitionByType($type: String!){
    metaobjectDefinitionByType(type: $type){
        access{
            admin
            storefront
        }
        createdByApp{
            apiKey
            appStoreAppUrl
            appStoreDeveloperUrl
            description
            developerName
            developerType
            embedded
            features
            handle
            id
            installUrl
            isPostPurchaseAppInUse
            previouslyInstalled
            pricingDetails
            pricingDetailsSummary
            privacyPolicyUrl
            publicCategory
            published
            shopifyDeveloped
            title
            uninstallMessage
            webhookApiVersion
        }
        createdByStaff{
            active
            email
            exists
            firstName
            id
            initials
            isShopOwner
            lastName
            locale
            name
            phone
        }
        description
        displayNameKey
        fieldDefinitions{
            description
            key
            name
            required
        }
        hasThumbnailField
        id
        metaobjectsCount
        name
        type
    }
}