query products($truncateAt: Int, $id: ID!, $context: ContextualPublicationContext!, $publicationId: ID!, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $sortKey: ProductSortKeys, $query: String, $savedSearchId: ID){
    products(first: $first, after: $after, last: $last, before: $before, reverse: $reverse, sortKey: $sortKey, query: $query, savedSearchId: $savedSearchId){
        edges{
            cursor
        }
        nodes{
            combinedListingRole
            createdAt
            defaultCursor
            description(truncateAt: $truncateAt)
            descriptionHtml
            giftCardTemplateSuffix
            handle
            hasOnlyDefaultVariant
            hasOutOfStockVariants
            hasVariantsThatRequiresComponents
            id
            inCollection(id: $id)
            isGiftCard
            legacyResourceId
            onlineStorePreviewUrl
            onlineStoreUrl
            productType
            publishedAt
            publishedInContext(context: $context)
            publishedOnCurrentPublication
            publishedOnPublication(publicationId: $publicationId)
            requiresSellingPlan
            status
            tags
            templateSuffix
            title
            totalInventory
            tracksInventory
            updatedAt
            vendor
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}