query returnCalculate($input: CalculateReturnInput!){
    returnCalculate(input: $input){
        exchangeLineItems{
            id
            quantity
        }
        id
        returnLineItems{
            id
            quantity
        }
        returnShippingFee{
            id
        }
    }
}