query segmentMigrations($savedSearchId: ID, $first: Int, $after: String, $last: Int, $before: String){
    segmentMigrations(savedSearchId: $savedSearchId, first: $first, after: $after, last: $last, before: $before){
        edges{
            cursor
        }
        nodes{
            id
            savedSearchId
            segmentId
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}