query shopLocales($published: Boolean){
    shopLocales(published: $published){
        locale
        marketWebPresences{
            id
            subfolderSuffix
        }
        name
        primary
        published
    }
}