query shopifyPaymentsAccount{
    shopifyPaymentsAccount{
        activated
        balance{
            amount
            currencyCode
        }
        chargeStatementDescriptors{
            default
            prefix
        }
        country
        defaultCurrency
        fraudSettings{
            declineChargeOnAvsFailure
            declineChargeOnCvcFailure
        }
        id
        notificationSettings{
            payouts
        }
        onboardable
        payoutSchedule{
            interval
            monthlyAnchor
            weeklyAnchor
        }
        payoutStatementDescriptor
        permittedVerificationDocuments{
            backRequired
            frontRequired
            type
        }
        verifications{
            id
            status
        }
    }
}