query subscriptionContract($showRevoked: Boolean, $id: ID!){
    subscriptionContract(id: $id){
        app{
            apiKey
            appStoreAppUrl
            appStoreDeveloperUrl
            description
            developerName
            developerType
            embedded
            features
            handle
            id
            installUrl
            isPostPurchaseAppInUse
            previouslyInstalled
            pricingDetails
            pricingDetailsSummary
            privacyPolicyUrl
            publicCategory
            published
            shopifyDeveloped
            title
            uninstallMessage
            webhookApiVersion
        }
        appAdminUrl
        billingPolicy{
            interval
            intervalCount
            maxCycles
            minCycles
        }
        createdAt
        currencyCode
        customAttributes{
            key
            value
        }
        customer{
            canDelete
            createdAt
            dataSaleOptOut
            displayName
            email
            firstName
            id
            lastName
            legacyResourceId
            lifetimeDuration
            locale
            multipassIdentifier
            note
            numberOfOrders
            phone
            productSubscriberStatus
            state
            tags
            taxExempt
            taxExemptions
            unsubscribeUrl
            updatedAt
            validEmailAddress
            verifiedEmail
        }
        customerPaymentMethod(showRevoked: $showRevoked){
            id
            instrument{
                __typename
                ... on CustomerCreditCard {
                    brand
                    expiresSoon
                    expiryMonth
                    expiryYear
                    firstDigits
                    isRevocable
                    lastDigits
                    maskedNumber
                    name
                    source
                    virtualLastDigits
                }
                ... on CustomerPaypalBillingAgreement {
                    inactive
                    isRevocable
                    paypalAccountEmail
                }
                ... on CustomerShopPayAgreement {
                    expiresSoon
                    expiryMonth
                    expiryYear
                    inactive
                    isRevocable
                    lastDigits
                    maskedNumber
                    name
                }
            }
            revokedAt
            revokedReason
        }
        deliveryMethod{
            __typename
            ... on SubscriptionDeliveryMethodLocalDelivery {
                address{
                    address1
                    address2
                    city
                    company
                    country
                    countryCode
                    firstName
                    lastName
                    name
                    phone
                    province
                    provinceCode
                    zip
                }
                localDeliveryOption{
                    code
                    description
                    instructions
                    phone
                    presentmentTitle
                    title
                }
            }
            ... on SubscriptionDeliveryMethodPickup {
                pickupOption{
                    code
                    description
                    presentmentTitle
                    title
                }
            }
            ... on SubscriptionDeliveryMethodShipping {
                shippingOption{
                    code
                    description
                    presentmentTitle
                    title
                }
            }
        }
        deliveryPolicy{
            interval
            intervalCount
        }
        deliveryPrice{
            amount
            currencyCode
        }
        id
        lastPaymentStatus
        linesCount{
            count
            precision
        }
        nextBillingDate
        note
        originOrder{
            billingAddressMatchesShippingAddress
            canMarkAsPaid
            canNotifyCustomer
            cancelReason
            cancelledAt
            capturable
            clientIp
            closed
            closedAt
            confirmationNumber
            confirmed
            createdAt
            currencyCode
            currentSubtotalLineItemsQuantity
            currentTotalWeight
            customerAcceptsMarketing
            customerLocale
            discountCode
            discountCodes
            displayFinancialStatus
            displayFulfillmentStatus
            edited
            email
            estimatedTaxes
            fulfillable
            fullyPaid
            hasTimelineComment
            id
            legacyResourceId
            merchantEditable
            merchantEditableErrors
            name
            note
            paymentGatewayNames
            phone
            poNumber
            presentmentCurrencyCode
            processedAt
            purchasingEntity{
                __typename
                ... on Customer {
                    canDelete
                    createdAt
                    dataSaleOptOut
                    displayName
                    email
                    firstName
                    hasTimelineComment
                    id
                    lastName
                    legacyResourceId
                    lifetimeDuration
                    locale
                    multipassIdentifier
                    note
                    numberOfOrders
                    phone
                    productSubscriberStatus
                    state
                    tags
                    taxExempt
                    taxExemptions
                    unsubscribeUrl
                    updatedAt
                    validEmailAddress
                    verifiedEmail
                }
            }
            refundable
            registeredSourceUrl
            requiresShipping
            restockable
            returnStatus
            sourceIdentifier
            sourceName
            subtotalLineItemsQuantity
            tags
            taxExempt
            taxesIncluded
            test
            totalWeight
            unpaid
            updatedAt
        }
        revisionId
        status
        updatedAt
    }
}