query translatableResourcesByIds($resourceIds: [ID!]!, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean){
    translatableResourcesByIds(resourceIds: $resourceIds, first: $first, after: $after, last: $last, before: $before, reverse: $reverse){
        edges{
            cursor
        }
        nodes{
            resourceId
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}