query urlRedirectSavedSearches($first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean){
    urlRedirectSavedSearches(first: $first, after: $after, last: $last, before: $before, reverse: $reverse){
        edges{
            cursor
        }
        nodes{
            id
            legacyResourceId
            name
            query
            resourceType
            searchTerms
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}