query catalogs($id: ID!, $id1: ID!, $type: CatalogType, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $sortKey: CatalogSortKeys, $query: String){
    catalogs(type: $type, first: $first, after: $after, last: $last, before: $before, reverse: $reverse, sortKey: $sortKey, query: $query){
        edges{
            cursor
            node{
                id
                operations{
                    id
                    processedRowCount
                    status
                }
                priceList{
                    currency
                    fixedPricesCount
                    id
                    name
                }
                publication{
                    autoPublish
                    hasCollection(id: $id)
                    id
                    name
                    operation{
                        __typename
                        ... on AddAllProductsOperation {
                            id
                            processedRowCount
                            status
                        }
                        ... on CatalogCsvOperation {
                            id
                            processedRowCount
                            status
                        }
                        ... on PublicationResourceOperation {
                            id
                            processedRowCount
                            status
                        }
                    }
                    supportsFuturePublishing
                }
                status
                title
            }
        }
        nodes{
            id
            operations{
                id
                processedRowCount
                rowCount{
                    count
                    exceedsMax
                }
                status
            }
            priceList{
                catalog{
                    id
                    status
                    title
                }
                currency
                fixedPricesCount
                id
                name
            }
            publication{
                app{
                    apiKey
                    appStoreAppUrl
                    appStoreDeveloperUrl
                    description
                    developerName
                    developerType
                    developerUrl
                    embedded
                    features
                    handle
                    id
                    installUrl
                    isPostPurchaseAppInUse
                    launchUrl
                    previouslyInstalled
                    pricingDetails
                    pricingDetailsSummary
                    privacyPolicyUrl
                    publicCategory
                    published
                    shopifyDeveloped
                    title
                    uninstallMessage
                    uninstallUrl
                    webhookApiVersion
                }
                autoPublish
                catalog{
                    id
                    status
                    title
                }
                hasCollection(id: $id1)
                id
                name
                operation{
                    __typename
                    ... on AddAllProductsOperation {
                        id
                        processedRowCount
                        rowCount{
                            count
                            exceedsMax
                        }
                        status
                    }
                    ... on CatalogCsvOperation {
                        id
                        processedRowCount
                        rowCount{
                            count
                            exceedsMax
                        }
                        status
                    }
                    ... on PublicationResourceOperation {
                        id
                        processedRowCount
                        rowCount{
                            count
                            exceedsMax
                        }
                        status
                    }
                }
                supportsFuturePublishing
            }
            status
            title
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}