query checkoutBranding($maxWidth: Int, $maxHeight: Int, $crop: CropRegion, $scale: Int, $preferredContentType: ImageContentType, $transform: ImageTransformInput, $checkoutProfileId: ID!){
    checkoutBranding(checkoutProfileId: $checkoutProfileId){
        customizations{
            buyerJourney{
                visibility
            }
            cartLink{
                visibility
            }
            checkbox{
                cornerRadius
            }
            choiceList{
                group{
                    spacing
                }
            }
            content{
                divider{
                    borderStyle
                    borderWidth
                    visibility
                }
            }
            control{
                border
                color
                cornerRadius
                labelPosition
            }
            divider{
                borderStyle
                borderWidth
            }
            expressCheckout{
                button{
                    cornerRadius
                }
            }
            favicon{
                image{
                    altText
                    height
                    id
                    originalSrc
                    src
                    transformedSrc(maxWidth: $maxWidth, maxHeight: $maxHeight, crop: $crop, scale: $scale, preferredContentType: $preferredContentType)
                    url(transform: $transform)
                    width
                }
            }
            footer{
                alignment
                colorScheme
                content{
                    visibility
                }
                divided
                padding
                position
            }
            global{
                cornerRadius
                typography{
                    kerning
                    letterCase
                }
            }
            header{
                alignment
                cartLink{
                    contentType
                }
                colorScheme
                divided
                logo{
                    maxWidth
                    visibility
                }
                padding
                position
            }
            headingLevel1{
                typography{
                    font
                    kerning
                    letterCase
                    size
                    weight
                }
            }
            headingLevel2{
                typography{
                    font
                    kerning
                    letterCase
                    size
                    weight
                }
            }
            headingLevel3{
                typography{
                    font
                    kerning
                    letterCase
                    size
                    weight
                }
            }
            main{
                colorScheme
                divider{
                    borderStyle
                    borderWidth
                    visibility
                }
                section{
                    background
                    border
                    borderStyle
                    borderWidth
                    colorScheme
                    cornerRadius
                    padding
                    shadow
                }
            }
            merchandiseThumbnail{
                border
                cornerRadius
            }
            orderSummary{
                colorScheme
                divider{
                    borderStyle
                    borderWidth
                    visibility
                }
                section{
                    background
                    border
                    borderStyle
                    borderWidth
                    colorScheme
                    cornerRadius
                    padding
                    shadow
                }
            }
            primaryButton{
                background
                blockPadding
                border
                cornerRadius
                inlinePadding
                typography{
                    font
                    kerning
                    letterCase
                    size
                    weight
                }
            }
            secondaryButton{
                background
                blockPadding
                border
                cornerRadius
                inlinePadding
                typography{
                    font
                    kerning
                    letterCase
                    size
                    weight
                }
            }
            select{
                border
                typography{
                    font
                    kerning
                    letterCase
                    size
                    weight
                }
            }
            textField{
                border
                typography{
                    font
                    kerning
                    letterCase
                    size
                    weight
                }
            }
        }
        designSystem{
            colors{
                global{
                    accent
                    brand
                    critical
                    decorative
                    info
                    success
                    warning
                }
            }
            cornerRadius{
                base
                large
                small
            }
            typography{
                primary{
                    loadingStrategy
                    name
                }
                secondary{
                    loadingStrategy
                    name
                }
                size{
                    base
                    ratio
                }
            }
        }
    }
}