query comments($query: String, $maxWidth: Int, $maxHeight: Int, $crop: CropRegion, $scale: Int, $preferredContentType: ImageContentType, $transform: ImageTransformInput, $truncateAt: Int, $id: ID!, $onlyPublished: Boolean, $channelId: ID!, $publicationId: ID!, $truncateAt1: Int, $id1: ID!, $onlyPublished1: Boolean, $context: ContextualPublicationContext!, $channelId1: ID!, $publicationId1: ID!, $namespace: String, $key: String!, $namespace1: String!, $key1: String!, $locale: String!, $marketId: ID, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $sortKey: EventSortKeys, $query1: String, $first1: Int, $after1: String, $last1: Int, $before1: String, $reverse1: Boolean, $sortKey1: CommentSortKeys, $query2: String){
    comments(first: $first1, after: $after1, last: $last1, before: $before1, reverse: $reverse1, sortKey: $sortKey1, query: $query2){
        edges{
            cursor
            node{
                article{
                    body
                    createdAt
                    defaultCursor
                    handle
                    id
                    isPublished
                    publishedAt
                    summary
                    tags
                    templateSuffix
                    title
                    updatedAt
                }
                author{
                    email
                    name
                }
                body
                bodyHtml
                createdAt
                id
                ip
                isPublished
                publishedAt
                status
                updatedAt
                userAgent
            }
        }
        nodes{
            article{
                author{
                    name
                }
                blog{
                    commentPolicy
                    createdAt
                    handle
                    id
                    tags
                    templateSuffix
                    title
                    updatedAt
                }
                body
                commentsCount(query: $query){
                    count
                    precision
                }
                createdAt
                defaultCursor
                handle
                id
                image{
                    altText
                    height
                    id
                    originalSrc
                    src
                    transformedSrc(maxWidth: $maxWidth, maxHeight: $maxHeight, crop: $crop, scale: $scale, preferredContentType: $preferredContentType)
                    url(transform: $transform)
                    width
                }
                isPublished
                metafield(namespace: $namespace, key: $key){
                    compareDigest
                    createdAt
                    description
                    id
                    jsonValue
                    key
                    legacyResourceId
                    namespace
                    ownerType
                    reference{
                        __typename
                        ... on Collection {
                            description(truncateAt: $truncateAt)
                            descriptionHtml
                            handle
                            hasProduct(id: $id)
                            id
                            legacyResourceId
                            publicationCount(onlyPublished: $onlyPublished)
                            publishedOnChannel(channelId: $channelId)
                            publishedOnCurrentChannel
                            publishedOnCurrentPublication
                            publishedOnPublication(publicationId: $publicationId)
                            sortOrder
                            storefrontId
                            templateSuffix
                            title
                            updatedAt
                        }
                        ... on Company {
                            contactCount
                            createdAt
                            customerSince
                            defaultCursor
                            externalId
                            hasTimelineComment
                            id
                            lifetimeDuration
                            name
                            note
                            updatedAt
                        }
                        ... on Customer {
                            canDelete
                            createdAt
                            dataSaleOptOut
                            displayName
                            email
                            firstName
                            hasTimelineComment
                            id
                            lastName
                            legacyResourceId
                            lifetimeDuration
                            locale
                            multipassIdentifier
                            note
                            numberOfOrders
                            phone
                            productSubscriberStatus
                            state
                            tags
                            taxExempt
                            taxExemptions
                            unsubscribeUrl
                            updatedAt
                            validEmailAddress
                            verifiedEmail
                        }
                        ... on GenericFile {
                            alt
                            createdAt
                            fileStatus
                            id
                            mimeType
                            originalFileSize
                            updatedAt
                            url
                        }
                        ... on MediaImage {
                            alt
                            createdAt
                            fileStatus
                            id
                            mediaContentType
                            mimeType
                            status
                            updatedAt
                        }
                        ... on Metaobject {
                            displayName
                            handle
                            id
                            type
                            updatedAt
                        }
                        ... on Model3d {
                            alt
                            createdAt
                            fileStatus
                            filename
                            id
                            mediaContentType
                            status
                            updatedAt
                        }
                        ... on Order {
                            billingAddressMatchesShippingAddress
                            canMarkAsPaid
                            canNotifyCustomer
                            cancelReason
                            cancelledAt
                            capturable
                            cartDiscountAmount
                            clientIp
                            closed
                            closedAt
                            confirmationNumber
                            confirmed
                            createdAt
                            currencyCode
                            currentSubtotalLineItemsQuantity
                            currentTotalWeight
                            customerAcceptsMarketing
                            customerLocale
                            discountCode
                            discountCodes
                            displayFinancialStatus
                            displayFulfillmentStatus
                            dutiesIncluded
                            edited
                            email
                            estimatedTaxes
                            fulfillable
                            fullyPaid
                            hasTimelineComment
                            id
                            landingPageDisplayText
                            landingPageUrl
                            legacyResourceId
                            merchantEditable
                            merchantEditableErrors
                            name
                            netPayment
                            note
                            paymentGatewayNames
                            phone
                            poNumber
                            presentmentCurrencyCode
                            processedAt
                            purchasingEntity{
                                __typename
                                ... on Customer {
                                    canDelete
                                    createdAt
                                    dataSaleOptOut
                                    displayName
                                    email
                                    firstName
                                    hasTimelineComment
                                    id
                                    lastName
                                    legacyResourceId
                                    lifetimeDuration
                                    locale
                                    multipassIdentifier
                                    note
                                    numberOfOrders
                                    phone
                                    productSubscriberStatus
                                    state
                                    tags
                                    taxExempt
                                    taxExemptions
                                    unsubscribeUrl
                                    updatedAt
                                    validEmailAddress
                                    verifiedEmail
                                }
                            }
                            referralCode
                            referrerDisplayText
                            referrerUrl
                            refundable
                            registeredSourceUrl
                            requiresShipping
                            restockable
                            returnStatus
                            riskLevel
                            sourceIdentifier
                            sourceName
                            statusPageUrl
                            subtotalLineItemsQuantity
                            subtotalPrice
                            tags
                            taxExempt
                            taxesIncluded
                            test
                            totalCapturable
                            totalDiscounts
                            totalPrice
                            totalReceived
                            totalRefunded
                            totalShippingPrice
                            totalTax
                            totalWeight
                            unpaid
                            updatedAt
                        }
                        ... on Page {
                            body
                            bodySummary
                            createdAt
                            defaultCursor
                            handle
                            id
                            isPublished
                            publishedAt
                            templateSuffix
                            title
                            updatedAt
                        }
                        ... on Product {
                            bodyHtml
                            combinedListingRole
                            createdAt
                            customProductType
                            defaultCursor
                            description(truncateAt: $truncateAt1)
                            descriptionHtml
                            descriptionPlainSummary
                            giftCardTemplateSuffix
                            handle
                            hasOnlyDefaultVariant
                            hasOutOfStockVariants
                            hasVariantsThatRequiresComponents
                            id
                            inCollection(id: $id1)
                            isGiftCard
                            legacyResourceId
                            onlineStorePreviewUrl
                            onlineStoreUrl
                            productType
                            publicationCount(onlyPublished: $onlyPublished1)
                            publishedAt
                            publishedInContext(context: $context)
                            publishedOnChannel(channelId: $channelId1)
                            publishedOnCurrentChannel
                            publishedOnCurrentPublication
                            publishedOnPublication(publicationId: $publicationId1)
                            requiresSellingPlan
                            sellingPlanGroupCount
                            status
                            storefrontId
                            tags
                            templateSuffix
                            title
                            totalInventory
                            totalVariants
                            tracksInventory
                            updatedAt
                            vendor
                        }
                        ... on ProductVariant {
                            availableForSale
                            barcode
                            compareAtPrice
                            createdAt
                            defaultCursor
                            displayName
                            id
                            inventoryPolicy
                            inventoryQuantity
                            legacyResourceId
                            position
                            price
                            requiresComponents
                            sellableOnlineQuantity
                            sellingPlanGroupCount
                            sku
                            storefrontId
                            taxCode
                            taxable
                            title
                            updatedAt
                        }
                        ... on TaxonomyValue {
                            id
                            name
                        }
                        ... on Video {
                            alt
                            createdAt
                            duration
                            fileStatus
                            filename
                            id
                            mediaContentType
                            status
                            updatedAt
                        }
                    }
                    type
                    updatedAt
                    value
                }
                privateMetafield(namespace: $namespace1, key: $key1){
                    createdAt
                    id
                    key
                    namespace
                    updatedAt
                    value
                    valueType
                }
                publishedAt
                summary
                tags
                templateSuffix
                title
                translations(locale: $locale, marketId: $marketId){
                    key
                    locale
                    outdated
                    updatedAt
                    value
                }
                updatedAt
            }
            author{
                email
                name
            }
            body
            bodyHtml
            createdAt
            events(first: $first, after: $after, last: $last, before: $before, reverse: $reverse, sortKey: $sortKey, query: $query1){
                edges{
                    cursor
                }
                nodes{
                    action
                    appTitle
                    attributeToApp
                    attributeToUser
                    createdAt
                    criticalAlert
                    id
                    message
                }
                pageInfo{
                    endCursor
                    hasNextPage
                    hasPreviousPage
                    startCursor
                }
            }
            id
            ip
            isPublished
            publishedAt
            status
            updatedAt
            userAgent
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}