query customerMergeJobStatus($jobId: ID!){
    customerMergeJobStatus(jobId: $jobId){
        customerMergeErrors{
            errorFields
            message
        }
        jobId
        resultingCustomerId
        status
    }
}