query marketLocalizableResourcesByIds($marketId: ID!, $marketId1: ID!, $resourceIds: [ID!]!, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean){
    marketLocalizableResourcesByIds(resourceIds: $resourceIds, first: $first, after: $after, last: $last, before: $before, reverse: $reverse){
        edges{
            cursor
            node{
                marketLocalizableContent{
                    digest
                    key
                    value
                }
                marketLocalizations(marketId: $marketId){
                    key
                    outdated
                    updatedAt
                    value
                }
                resourceId
            }
        }
        nodes{
            marketLocalizableContent{
                digest
                key
                value
            }
            marketLocalizations(marketId: $marketId1){
                key
                market{
                    enabled
                    handle
                    id
                    name
                    primary
                }
                outdated
                updatedAt
                value
            }
            resourceId
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}