query priceList($id: ID!, $originType: PriceListPriceOriginType, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $query: String, $originType1: QuantityRuleOriginType, $first1: Int, $after1: String, $last1: Int, $before1: String, $reverse1: Boolean, $id1: ID!){
    priceList(id: $id1){
        catalog{
            id
            operations{
                id
                processedRowCount
                rowCount{
                    count
                    exceedsMax
                }
                status
            }
            priceList{
                catalog{
                    id
                    status
                    title
                }
                currency
                fixedPricesCount
                id
                name
            }
            publication{
                app{
                    apiKey
                    appStoreAppUrl
                    appStoreDeveloperUrl
                    description
                    developerName
                    developerType
                    developerUrl
                    embedded
                    features
                    handle
                    id
                    installUrl
                    isPostPurchaseAppInUse
                    launchUrl
                    previouslyInstalled
                    pricingDetails
                    pricingDetailsSummary
                    privacyPolicyUrl
                    publicCategory
                    published
                    shopifyDeveloped
                    title
                    uninstallMessage
                    uninstallUrl
                    webhookApiVersion
                }
                autoPublish
                catalog{
                    id
                    status
                    title
                }
                hasCollection(id: $id)
                id
                name
                operation{
                    __typename
                    ... on AddAllProductsOperation {
                        id
                        processedRowCount
                        rowCount{
                            count
                            exceedsMax
                        }
                        status
                    }
                    ... on CatalogCsvOperation {
                        id
                        processedRowCount
                        rowCount{
                            count
                            exceedsMax
                        }
                        status
                    }
                    ... on PublicationResourceOperation {
                        id
                        processedRowCount
                        rowCount{
                            count
                            exceedsMax
                        }
                        status
                    }
                }
                supportsFuturePublishing
            }
            status
            title
        }
        currency
        fixedPricesCount
        id
        name
        parent{
            adjustment{
                type
                value
            }
            settings{
                compareAtMode
            }
        }
        prices(originType: $originType, first: $first, after: $after, last: $last, before: $before, reverse: $reverse, query: $query){
            edges{
                cursor
                node{
                    originType
                }
            }
            nodes{
                compareAtPrice{
                    amount
                    currencyCode
                }
                originType
                price{
                    amount
                    currencyCode
                }
                variant{
                    availableForSale
                    barcode
                    compareAtPrice
                    createdAt
                    defaultCursor
                    displayName
                    id
                    inventoryPolicy
                    inventoryQuantity
                    legacyResourceId
                    position
                    price
                    requiresComponents
                    sellableOnlineQuantity
                    sellingPlanGroupCount
                    sku
                    storefrontId
                    taxCode
                    taxable
                    title
                    updatedAt
                }
            }
            pageInfo{
                endCursor
                hasNextPage
                hasPreviousPage
                startCursor
            }
        }
        quantityRules(originType: $originType1, first: $first1, after: $after1, last: $last1, before: $before1, reverse: $reverse1){
            edges{
                cursor
                node{
                    increment
                    isDefault
                    maximum
                    minimum
                    originType
                }
            }
            nodes{
                increment
                isDefault
                maximum
                minimum
                originType
                productVariant{
                    availableForSale
                    barcode
                    compareAtPrice
                    createdAt
                    defaultCursor
                    displayName
                    id
                    inventoryPolicy
                    inventoryQuantity
                    legacyResourceId
                    position
                    price
                    requiresComponents
                    sellableOnlineQuantity
                    sellingPlanGroupCount
                    sku
                    storefrontId
                    taxCode
                    taxable
                    title
                    updatedAt
                }
            }
            pageInfo{
                endCursor
                hasNextPage
                hasPreviousPage
                startCursor
            }
        }
    }
}