query priceLists($id: ID!, $originType: PriceListPriceOriginType, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $query: String, $originType1: QuantityRuleOriginType, $first1: Int, $after1: String, $last1: Int, $before1: String, $reverse1: Boolean, $first2: Int, $after2: String, $last2: Int, $before2: String, $reverse2: Boolean, $sortKey: PriceListSortKeys){
    priceLists(first: $first2, after: $after2, last: $last2, before: $before2, reverse: $reverse2, sortKey: $sortKey){
        edges{
            cursor
            node{
                catalog{
                    id
                    status
                    title
                }
                currency
                fixedPricesCount
                id
                name
            }
        }
        nodes{
            catalog{
                id
                operations{
                    id
                    processedRowCount
                    status
                }
                priceList{
                    currency
                    fixedPricesCount
                    id
                    name
                }
                publication{
                    autoPublish
                    hasCollection(id: $id)
                    id
                    name
                    operation{
                        __typename
                        ... on AddAllProductsOperation {
                            id
                            processedRowCount
                            status
                        }
                        ... on CatalogCsvOperation {
                            id
                            processedRowCount
                            status
                        }
                        ... on PublicationResourceOperation {
                            id
                            processedRowCount
                            status
                        }
                    }
                    supportsFuturePublishing
                }
                status
                title
            }
            currency
            fixedPricesCount
            id
            name
            parent{
                adjustment{
                    type
                    value
                }
                settings{
                    compareAtMode
                }
            }
            prices(originType: $originType, first: $first, after: $after, last: $last, before: $before, reverse: $reverse, query: $query){
                edges{
                    cursor
                }
                nodes{
                    originType
                }
                pageInfo{
                    endCursor
                    hasNextPage
                    hasPreviousPage
                    startCursor
                }
            }
            quantityRules(originType: $originType1, first: $first1, after: $after1, last: $last1, before: $before1, reverse: $reverse1){
                edges{
                    cursor
                }
                nodes{
                    increment
                    isDefault
                    maximum
                    minimum
                    originType
                }
                pageInfo{
                    endCursor
                    hasNextPage
                    hasPreviousPage
                    startCursor
                }
            }
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}