query returnableFulfillments($first: Int, $first1: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $orderId: ID!, $first2: Int, $after1: String, $last1: Int, $before1: String, $reverse1: Boolean){
    returnableFulfillments(orderId: $orderId, first: $first2, after: $after1, last: $last1, before: $before1, reverse: $reverse1){
        edges{
            cursor
            node{
                fulfillment{
                    createdAt
                    deliveredAt
                    displayStatus
                    estimatedDeliveryAt
                    id
                    inTransitAt
                    legacyResourceId
                    name
                    requiresShipping
                    status
                    totalQuantity
                    updatedAt
                }
                id
            }
        }
        nodes{
            fulfillment{
                createdAt
                deliveredAt
                displayStatus
                estimatedDeliveryAt
                id
                inTransitAt
                legacyResourceId
                location{
                    activatable
                    addressVerified
                    createdAt
                    deactivatable
                    deactivatedAt
                    deletable
                    fulfillsOnlineOrders
                    hasActiveInventory
                    hasUnfulfilledOrders
                    id
                    isActive
                    isFulfillmentService
                    isPrimary
                    legacyResourceId
                    name
                    shipsInventory
                    updatedAt
                }
                name
                order{
                    billingAddressMatchesShippingAddress
                    canMarkAsPaid
                    canNotifyCustomer
                    cancelReason
                    cancelledAt
                    capturable
                    cartDiscountAmount
                    clientIp
                    closed
                    closedAt
                    confirmationNumber
                    confirmed
                    createdAt
                    currencyCode
                    currentSubtotalLineItemsQuantity
                    currentTotalWeight
                    customerAcceptsMarketing
                    customerLocale
                    discountCode
                    discountCodes
                    displayFinancialStatus
                    displayFulfillmentStatus
                    dutiesIncluded
                    edited
                    email
                    estimatedTaxes
                    fulfillable
                    fullyPaid
                    hasTimelineComment
                    id
                    landingPageDisplayText
                    landingPageUrl
                    legacyResourceId
                    merchantEditable
                    merchantEditableErrors
                    name
                    netPayment
                    note
                    paymentGatewayNames
                    phone
                    poNumber
                    presentmentCurrencyCode
                    processedAt
                    purchasingEntity{
                        __typename
                        ... on Customer {
                            canDelete
                            createdAt
                            dataSaleOptOut
                            displayName
                            email
                            firstName
                            hasTimelineComment
                            id
                            lastName
                            legacyResourceId
                            lifetimeDuration
                            locale
                            multipassIdentifier
                            note
                            numberOfOrders
                            phone
                            productSubscriberStatus
                            state
                            tags
                            taxExempt
                            taxExemptions
                            unsubscribeUrl
                            updatedAt
                            validEmailAddress
                            verifiedEmail
                        }
                    }
                    referralCode
                    referrerDisplayText
                    referrerUrl
                    refundable
                    registeredSourceUrl
                    requiresShipping
                    restockable
                    returnStatus
                    riskLevel
                    sourceIdentifier
                    sourceName
                    statusPageUrl
                    subtotalLineItemsQuantity
                    subtotalPrice
                    tags
                    taxExempt
                    taxesIncluded
                    test
                    totalCapturable
                    totalDiscounts
                    totalPrice
                    totalReceived
                    totalRefunded
                    totalShippingPrice
                    totalTax
                    totalWeight
                    unpaid
                    updatedAt
                }
                originAddress{
                    address1
                    address2
                    city
                    countryCode
                    provinceCode
                    zip
                }
                requiresShipping
                service{
                    callbackUrl
                    fulfillmentOrdersOptIn
                    handle
                    id
                    inventoryManagement
                    permitsSkuSharing
                    serviceName
                    trackingSupport
                    type
                }
                status
                totalQuantity
                trackingInfo(first: $first){
                    company
                    number
                    url
                }
                updatedAt
            }
            id
            returnableFulfillmentLineItems(first: $first1, after: $after, last: $last, before: $before, reverse: $reverse){
                edges{
                    cursor
                }
                nodes{
                    quantity
                }
                pageInfo{
                    endCursor
                    hasNextPage
                    hasPreviousPage
                    startCursor
                }
            }
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}