query shopifyPaymentsAccount($hideTransfers: Boolean, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $sortKey: BalanceTransactionSortKeys, $query: String, $savedSearchId: ID, $first1: Int, $after1: String, $last1: Int, $before1: String, $reverse1: Boolean, $first2: Int, $after2: String, $last2: Int, $before2: String, $reverse2: Boolean, $query1: String, $transactionType: ShopifyPaymentsPayoutTransactionType, $first3: Int, $after3: String, $last3: Int, $before3: String, $reverse3: Boolean, $sortKey1: PayoutSortKeys, $query2: String, $savedSearchId1: ID){
    shopifyPaymentsAccount{
        activated
        balance{
            amount
            currencyCode
        }
        balanceTransactions(hideTransfers: $hideTransfers, first: $first, after: $after, last: $last, before: $before, reverse: $reverse, sortKey: $sortKey, query: $query, savedSearchId: $savedSearchId){
            edges{
                cursor
                node{
                    adjustmentReason
                    id
                    sourceId
                    sourceOrderTransactionId
                    sourceType
                    test
                    transactionDate
                    type
                }
            }
            nodes{
                adjustmentReason
                adjustmentsOrders{
                    link
                    name
                    orderTransactionId
                }
                amount{
                    amount
                    currencyCode
                }
                associatedOrder{
                    id
                    name
                }
                associatedPayout{
                    id
                    status
                }
                fee{
                    amount
                    currencyCode
                }
                id
                net{
                    amount
                    currencyCode
                }
                sourceId
                sourceOrderTransactionId
                sourceType
                test
                transactionDate
                type
            }
            pageInfo{
                endCursor
                hasNextPage
                hasPreviousPage
                startCursor
            }
        }
        bankAccounts(first: $first1, after: $after1, last: $last1, before: $before1, reverse: $reverse1){
            edges{
                cursor
                node{
                    accountNumber
                    accountNumberLastDigits
                    bankName
                    country
                    createdAt
                    currency
                    id
                    routingNumber
                    status
                }
            }
            nodes{
                accountNumber
                accountNumberLastDigits
                bankName
                country
                createdAt
                currency
                id
                routingNumber
                status
            }
            pageInfo{
                endCursor
                hasNextPage
                hasPreviousPage
                startCursor
            }
        }
        chargeStatementDescriptor
        chargeStatementDescriptors{
            default
            prefix
        }
        country
        defaultCurrency
        disputes(first: $first2, after: $after2, last: $last2, before: $before2, reverse: $reverse2, query: $query1){
            edges{
                cursor
                node{
                    evidenceDueBy
                    evidenceSentOn
                    finalizedOn
                    id
                    initiatedAt
                    legacyResourceId
                    status
                    type
                }
            }
            nodes{
                amount{
                    amount
                    currencyCode
                }
                evidenceDueBy
                evidenceSentOn
                finalizedOn
                id
                initiatedAt
                legacyResourceId
                order{
                    billingAddressMatchesShippingAddress
                    canMarkAsPaid
                    canNotifyCustomer
                    cancelReason
                    cancelledAt
                    capturable
                    cartDiscountAmount
                    clientIp
                    closed
                    closedAt
                    confirmationNumber
                    confirmed
                    createdAt
                    currencyCode
                    currentSubtotalLineItemsQuantity
                    currentTotalWeight
                    customerAcceptsMarketing
                    customerLocale
                    discountCode
                    discountCodes
                    displayFinancialStatus
                    displayFulfillmentStatus
                    dutiesIncluded
                    edited
                    email
                    estimatedTaxes
                    fulfillable
                    fullyPaid
                    hasTimelineComment
                    id
                    landingPageDisplayText
                    landingPageUrl
                    legacyResourceId
                    merchantEditable
                    merchantEditableErrors
                    name
                    netPayment
                    note
                    paymentGatewayNames
                    phone
                    poNumber
                    presentmentCurrencyCode
                    processedAt
                    purchasingEntity{
                        __typename
                        ... on Customer {
                            canDelete
                            createdAt
                            dataSaleOptOut
                            displayName
                            email
                            firstName
                            hasTimelineComment
                            id
                            lastName
                            legacyResourceId
                            lifetimeDuration
                            locale
                            multipassIdentifier
                            note
                            numberOfOrders
                            phone
                            productSubscriberStatus
                            state
                            tags
                            taxExempt
                            taxExemptions
                            unsubscribeUrl
                            updatedAt
                            validEmailAddress
                            verifiedEmail
                        }
                    }
                    referralCode
                    referrerDisplayText
                    referrerUrl
                    refundable
                    registeredSourceUrl
                    requiresShipping
                    restockable
                    returnStatus
                    riskLevel
                    sourceIdentifier
                    sourceName
                    statusPageUrl
                    subtotalLineItemsQuantity
                    subtotalPrice
                    tags
                    taxExempt
                    taxesIncluded
                    test
                    totalCapturable
                    totalDiscounts
                    totalPrice
                    totalReceived
                    totalRefunded
                    totalShippingPrice
                    totalTax
                    totalWeight
                    unpaid
                    updatedAt
                }
                reasonDetails{
                    networkReasonCode
                    reason
                }
                status
                type
            }
            pageInfo{
                endCursor
                hasNextPage
                hasPreviousPage
                startCursor
            }
        }
        id
        onboardable
        payoutSchedule{
            interval
            monthlyAnchor
            weeklyAnchor
        }
        payoutStatementDescriptor
        payouts(transactionType: $transactionType, first: $first3, after: $after3, last: $last3, before: $before3, reverse: $reverse3, sortKey: $sortKey1, query: $query2, savedSearchId: $savedSearchId1){
            edges{
                cursor
                node{
                    id
                    issuedAt
                    legacyResourceId
                    status
                    transactionType
                }
            }
            nodes{
                bankAccount{
                    accountNumber
                    accountNumberLastDigits
                    bankName
                    country
                    createdAt
                    currency
                    id
                    routingNumber
                    status
                }
                businessEntity{
                    companyName
                    displayName
                    id
                    primary
                }
                gross{
                    amount
                    currencyCode
                }
                id
                issuedAt
                legacyResourceId
                net{
                    amount
                    currencyCode
                }
                status
                transactionType
            }
            pageInfo{
                endCursor
                hasNextPage
                hasPreviousPage
                startCursor
            }
        }
    }
}