query shopifyFunctions($maxWidth: Int, $maxHeight: Int, $crop: CropRegion, $scale: Int, $preferredContentType: ImageContentType, $transform: ImageTransformInput, $maxWidth1: Int, $maxHeight1: Int, $crop1: CropRegion, $scale1: Int, $preferredContentType1: ImageContentType, $transform1: ImageTransformInput, $maxWidth2: Int, $maxHeight2: Int, $crop2: CropRegion, $scale2: Int, $preferredContentType2: ImageContentType, $transform2: ImageTransformInput, $apiType: String, $useCreationUi: Boolean, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean){
    shopifyFunctions(apiType: $apiType, useCreationUi: $useCreationUi, first: $first, after: $after, last: $last, before: $before, reverse: $reverse){
        edges{
            cursor
            node{
                apiType
                apiVersion
                app{
                    apiKey
                    appStoreAppUrl
                    appStoreDeveloperUrl
                    description
                    developerName
                    developerType
                    developerUrl
                    embedded
                    features
                    handle
                    id
                    installUrl
                    isPostPurchaseAppInUse
                    launchUrl
                    previouslyInstalled
                    pricingDetails
                    pricingDetailsSummary
                    privacyPolicyUrl
                    publicCategory
                    published
                    shopifyDeveloped
                    title
                    uninstallMessage
                    uninstallUrl
                    webhookApiVersion
                }
                appBridge{
                    createPath
                    detailsPath
                }
                appKey
                description
                id
                inputQuery
                title
                useCreationUi
            }
        }
        nodes{
            apiType
            apiVersion
            app{
                apiKey
                appStoreAppUrl
                appStoreDeveloperUrl
                availableAccessScopes{
                    description
                    handle
                }
                banner{
                    altText
                    height
                    id
                    originalSrc
                    src
                    transformedSrc(maxWidth: $maxWidth, maxHeight: $maxHeight, crop: $crop, scale: $scale, preferredContentType: $preferredContentType)
                    url(transform: $transform)
                    width
                }
                description
                developerName
                developerType
                developerUrl
                embedded
                failedRequirements{
                    message
                }
                features
                feedback{
                    feedbackGeneratedAt
                    state
                }
                handle
                icon{
                    altText
                    height
                    id
                    originalSrc
                    src
                    transformedSrc(maxWidth: $maxWidth1, maxHeight: $maxHeight1, crop: $crop1, scale: $scale1, preferredContentType: $preferredContentType1)
                    url(transform: $transform1)
                    width
                }
                id
                installUrl
                installation{
                    id
                    launchUrl
                    uninstallUrl
                }
                isPostPurchaseAppInUse
                launchUrl
                navigationItems{
                    id
                    title
                    url
                }
                optionalAccessScopes{
                    description
                    handle
                }
                previouslyInstalled
                pricingDetails
                pricingDetailsSummary
                privacyPolicyUrl
                publicCategory
                published
                requestedAccessScopes{
                    description
                    handle
                }
                screenshots{
                    altText
                    height
                    id
                    originalSrc
                    src
                    transformedSrc(maxWidth: $maxWidth2, maxHeight: $maxHeight2, crop: $crop2, scale: $scale2, preferredContentType: $preferredContentType2)
                    url(transform: $transform2)
                    width
                }
                shopifyDeveloped
                title
                uninstallMessage
                uninstallUrl
                webhookApiVersion
            }
            appBridge{
                createPath
                detailsPath
            }
            appKey
            description
            id
            inputQuery
            title
            useCreationUi
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}