query themes($locale: String!, $marketId: ID, $filenames: [String!], $first: Int, $after: String, $locale1: String!, $marketId1: ID, $roles: [ThemeRole!], $names: [String!], $first1: Int, $after1: String, $last: Int, $before: String, $reverse: Boolean){
    themes(roles: $roles, names: $names, first: $first1, after: $after1, last: $last, before: $before, reverse: $reverse){
        edges{
            cursor
            node{
                createdAt
                id
                name
                prefix
                processing
                processingFailed
                role
                themeStoreId
                translations(locale: $locale, marketId: $marketId){
                    key
                    locale
                    outdated
                    updatedAt
                    value
                }
                updatedAt
            }
        }
        nodes{
            createdAt
            files(filenames: $filenames, first: $first, after: $after){
                edges{
                    cursor
                }
                nodes{
                    body{
                        __typename
                        ... on OnlineStoreThemeFileBodyBase64 {
                            contentBase64
                        }
                        ... on OnlineStoreThemeFileBodyText {
                            content
                        }
                        ... on OnlineStoreThemeFileBodyUrl {
                            url
                        }
                    }
                    checksumMd5
                    contentType
                    createdAt
                    filename
                    size
                    updatedAt
                }
                pageInfo{
                    endCursor
                    hasNextPage
                    hasPreviousPage
                    startCursor
                }
                userErrors{
                    code
                    filename
                }
            }
            id
            name
            prefix
            processing
            processingFailed
            role
            themeStoreId
            translations(locale: $locale1, marketId: $marketId1){
                key
                locale
                market{
                    enabled
                    handle
                    id
                    name
                    primary
                }
                outdated
                updatedAt
                value
            }
            updatedAt
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}