query abandonedCheckouts($withName: Boolean, $withCompany: Boolean, $withName1: Boolean, $withCompany1: Boolean, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $sortKey: AbandonedCheckoutSortKeys, $query: String, $savedSearchId: ID){
    abandonedCheckouts(first: $first, after: $after, last: $last, before: $before, reverse: $reverse, sortKey: $sortKey, query: $query, savedSearchId: $savedSearchId){
        edges{
            cursor
            node{
                abandonedCheckoutUrl
                completedAt
                createdAt
                defaultCursor
                discountCodes
                id
                name
                note
                taxesIncluded
                updatedAt
            }
        }
        nodes{
            abandonedCheckoutUrl
            billingAddress{
                address1
                address2
                city
                company
                coordinatesValidated
                country
                countryCodeV2
                firstName
                formatted(withName: $withName, withCompany: $withCompany)
                formattedArea
                id
                lastName
                latitude
                longitude
                name
                phone
                province
                provinceCode
                timeZone
                validationResultSummary
                zip
            }
            completedAt
            createdAt
            customAttributes{
                key
                value
            }
            customer{
                canDelete
                createdAt
                dataSaleOptOut
                displayName
                firstName
                id
                lastName
                legacyResourceId
                lifetimeDuration
                locale
                multipassIdentifier
                note
                numberOfOrders
                productSubscriberStatus
                state
                tags
                taxExempt
                taxExemptions
                updatedAt
                verifiedEmail
            }
            defaultCursor
            discountCodes
            id
            name
            note
            shippingAddress{
                address1
                address2
                city
                company
                coordinatesValidated
                country
                countryCodeV2
                firstName
                formatted(withName: $withName1, withCompany: $withCompany1)
                formattedArea
                id
                lastName
                latitude
                longitude
                name
                phone
                province
                provinceCode
                timeZone
                validationResultSummary
                zip
            }
            taxLines{
                channelLiable
                rate
                ratePercentage
                source
                title
            }
            taxesIncluded
            updatedAt
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}