query appDiscountTypesNodes($first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean){
    appDiscountTypesNodes(first: $first, after: $after, last: $last, before: $before, reverse: $reverse){
        edges{
            cursor
            node{
                appKey
                description
                discountClasses
                functionId
                title
            }
        }
        nodes{
            app{
                apiKey
                appStoreAppUrl
                appStoreDeveloperUrl
                description
                developerName
                developerType
                embedded
                features
                handle
                id
                installUrl
                isPostPurchaseAppInUse
                previouslyInstalled
                pricingDetails
                pricingDetailsSummary
                privacyPolicyUrl
                publicCategory
                published
                shopifyDeveloped
                title
                uninstallMessage
                webhookApiVersion
            }
            appBridge{
                createPath
                detailsPath
            }
            appKey
            description
            discountClasses
            functionId
            title
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}