query assignedFulfillmentOrders($audience: Audience, $notificationUsage: NotificationUsage, $assignmentStatus: FulfillmentOrderAssignmentStatus, $locationIds: [ID!], $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $sortKey: FulfillmentOrderSortKeys){
    assignedFulfillmentOrders(assignmentStatus: $assignmentStatus, locationIds: $locationIds, first: $first, after: $after, last: $last, before: $before, reverse: $reverse, sortKey: $sortKey){
        edges{
            cursor
            node{
                channelId
                createdAt
                fulfillAt
                fulfillBy
                id
                orderId
                orderName
                orderProcessedAt
                requestStatus
                status
                updatedAt
            }
        }
        nodes{
            assignedLocation{
                address1
                address2
                city
                countryCode
                name
                phone
                province
                zip
            }
            channelId
            createdAt
            deliveryMethod{
                id
                maxDeliveryDateTime
                methodType
                minDeliveryDateTime
                presentedName
                serviceCode
                sourceReference
            }
            destination{
                address1
                address2
                city
                company
                countryCode
                email
                firstName
                id
                lastName
                phone
                province
                zip
            }
            fulfillAt
            fulfillBy
            fulfillmentHolds{
                displayReason
                handle
                heldByRequestingApp
                id
                reason
                reasonNotes
            }
            id
            internationalDuties{
                incoterm
            }
            order{
                billingAddressMatchesShippingAddress
                canMarkAsPaid
                canNotifyCustomer
                cancelReason
                cancelledAt
                capturable
                clientIp
                closed
                closedAt
                confirmationNumber
                confirmed
                createdAt
                currencyCode
                currentSubtotalLineItemsQuantity
                currentTotalWeight
                customerAcceptsMarketing
                customerLocale
                discountCode
                discountCodes
                displayFinancialStatus
                displayFulfillmentStatus
                dutiesIncluded
                edited
                email
                estimatedTaxes
                fulfillable
                fullyPaid
                hasTimelineComment
                id
                legacyResourceId
                merchantEditable
                merchantEditableErrors
                name
                note
                number
                paymentGatewayNames
                phone
                poNumber
                presentmentCurrencyCode
                processedAt
                productNetwork
                purchasingEntity{
                    __typename
                    ... on Customer {
                        canDelete
                        createdAt
                        dataSaleOptOut
                        displayName
                        email
                        firstName
                        hasTimelineComment
                        id
                        lastName
                        legacyResourceId
                        lifetimeDuration
                        locale
                        multipassIdentifier
                        note
                        numberOfOrders
                        phone
                        productSubscriberStatus
                        state
                        tags
                        taxExempt
                        taxExemptions
                        unsubscribeUrl
                        updatedAt
                        validEmailAddress
                        verifiedEmail
                    }
                }
                refundable
                registeredSourceUrl
                requiresShipping
                restockable
                returnStatus
                sourceIdentifier
                sourceName
                statusPageUrl(audience: $audience, notificationUsage: $notificationUsage)
                subtotalLineItemsQuantity
                tags
                taxExempt
                taxesIncluded
                test
                totalWeight
                unpaid
                updatedAt
            }
            orderId
            orderName
            orderProcessedAt
            requestStatus
            status
            supportedActions{
                action
                externalUrl
            }
            updatedAt
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}