query comments($first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $sortKey: CommentSortKeys, $query: String){
    comments(first: $first, after: $after, last: $last, before: $before, reverse: $reverse, sortKey: $sortKey, query: $query){
        edges{
            cursor
            node{
                body
                bodyHtml
                createdAt
                id
                ip
                isPublished
                publishedAt
                status
                updatedAt
                userAgent
            }
        }
        nodes{
            article{
                body
                createdAt
                defaultCursor
                handle
                id
                isPublished
                publishedAt
                summary
                tags
                templateSuffix
                title
                updatedAt
            }
            author{
                email
                name
            }
            body
            bodyHtml
            createdAt
            id
            ip
            isPublished
            publishedAt
            status
            updatedAt
            userAgent
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}