query customerMergePreview($withName: Boolean, $withCompany: Boolean, $withName1: Boolean, $withCompany1: Boolean, $customerOneId: ID!, $customerTwoId: ID!, $overrideFields: CustomerMergeOverrideFields){
    customerMergePreview(customerOneId: $customerOneId, customerTwoId: $customerTwoId, overrideFields: $overrideFields){
        alternateFields{
            defaultAddress{
                address1
                address2
                city
                company
                coordinatesValidated
                country
                countryCodeV2
                firstName
                formatted(withName: $withName, withCompany: $withCompany)
                formattedArea
                id
                lastName
                latitude
                longitude
                name
                phone
                province
                provinceCode
                timeZone
                validationResultSummary
                zip
            }
            email{
                emailAddress
                marketingOptInLevel
                marketingState
                marketingUnsubscribeUrl
                marketingUpdatedAt
                openTrackingLevel
                openTrackingUrl
                validFormat
            }
            firstName
            lastName
            phoneNumber{
                marketingCollectedFrom
                marketingOptInLevel
                marketingState
                marketingUpdatedAt
                phoneNumber
            }
        }
        blockingFields{
            note
            tags
        }
        customerMergeErrors{
            errorFields
            message
        }
        defaultFields{
            defaultAddress{
                address1
                address2
                city
                company
                coordinatesValidated
                country
                countryCodeV2
                firstName
                formatted(withName: $withName1, withCompany: $withCompany1)
                formattedArea
                id
                lastName
                latitude
                longitude
                name
                phone
                province
                provinceCode
                timeZone
                validationResultSummary
                zip
            }
            discountNodeCount
            displayName
            draftOrderCount
            email{
                emailAddress
                marketingOptInLevel
                marketingState
                marketingUnsubscribeUrl
                marketingUpdatedAt
                openTrackingLevel
                openTrackingUrl
                validFormat
            }
            firstName
            giftCardCount
            lastName
            metafieldCount
            note
            orderCount
            phoneNumber{
                marketingCollectedFrom
                marketingOptInLevel
                marketingState
                marketingUpdatedAt
                phoneNumber
            }
            tags
        }
        resultingCustomerId
    }
}