query domain($id: ID!){
    domain(id: $id){
        host
        id
        localization{
            alternateLocales
            country
            defaultLocale
        }
        marketWebPresence{
            alternateLocales{
                locale
                name
                primary
                published
            }
            defaultLocale{
                locale
                name
                primary
                published
            }
            domain{
                host
                id
                sslEnabled
                url
            }
            id
            rootUrls{
                locale
                url
            }
            subfolderSuffix
        }
        sslEnabled
        url
    }
}