query files($first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $sortKey: FileSortKeys, $query: String, $savedSearchId: ID){
    files(first: $first, after: $after, last: $last, before: $before, reverse: $reverse, sortKey: $sortKey, query: $query, savedSearchId: $savedSearchId){
        edges{
            cursor
            node{
                alt
                createdAt
                fileStatus
                id
                updatedAt
            }
        }
        nodes{
            alt
            createdAt
            fileErrors{
                code
                details
                message
            }
            fileStatus
            id
            preview{
                status
            }
            updatedAt
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}