query inventoryItems($locationId: ID!, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $query: String){
    inventoryItems(first: $first, after: $after, last: $last, before: $before, reverse: $reverse, query: $query){
        edges{
            cursor
            node{
                countryCodeOfOrigin
                createdAt
                duplicateSkuCount
                harmonizedSystemCode
                id
                inventoryHistoryUrl
                legacyResourceId
                provinceCodeOfOrigin
                requiresShipping
                sku
                tracked
                updatedAt
            }
        }
        nodes{
            countryCodeOfOrigin
            createdAt
            duplicateSkuCount
            harmonizedSystemCode
            id
            inventoryHistoryUrl
            inventoryLevel(locationId: $locationId){
                canDeactivate
                createdAt
                deactivationAlert
                id
                updatedAt
            }
            legacyResourceId
            locationsCount{
                count
                precision
            }
            measurement{
                id
            }
            provinceCodeOfOrigin
            requiresShipping
            sku
            tracked
            trackedEditable{
                locked
                reason
            }
            unitCost{
                amount
                currencyCode
            }
            updatedAt
            variant{
                availableForSale
                barcode
                compareAtPrice
                createdAt
                defaultCursor
                displayName
                id
                inventoryPolicy
                inventoryQuantity
                legacyResourceId
                position
                price
                requiresComponents
                sellableOnlineQuantity
                showUnitPrice
                sku
                taxable
                title
                updatedAt
            }
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}