query marketingActivity($transform: ImageTransformInput, $transform1: ImageTransformInput, $transform2: ImageTransformInput, $id: ID!){
    marketingActivity(id: $id){
        activityListUrl
        adSpend{
            amount
            currencyCode
        }
        app{
            apiKey
            appStoreAppUrl
            appStoreDeveloperUrl
            availableAccessScopes{
                description
                handle
            }
            banner{
                altText
                height
                id
                thumbhash
                url(transform: $transform)
                width
            }
            description
            developerName
            developerType
            embedded
            failedRequirements{
                message
            }
            features
            feedback{
                feedbackGeneratedAt
                state
            }
            handle
            icon{
                altText
                height
                id
                thumbhash
                url(transform: $transform1)
                width
            }
            id
            installUrl
            installation{
                id
                launchUrl
                uninstallUrl
            }
            isPostPurchaseAppInUse
            optionalAccessScopes{
                description
                handle
            }
            previouslyInstalled
            pricingDetails
            pricingDetailsSummary
            privacyPolicyUrl
            publicCategory
            published
            requestedAccessScopes{
                description
                handle
            }
            screenshots{
                altText
                height
                id
                thumbhash
                url(transform: $transform2)
                width
            }
            shopifyDeveloped
            title
            uninstallMessage
            webhookApiVersion
        }
        appErrors{
            code
            userErrors{
                field
                message
            }
        }
        budget{
            budgetType
            total{
                amount
                currencyCode
            }
        }
        createdAt
        formData
        hierarchyLevel
        id
        inMainWorkflowVersion
        isExternal
        marketingChannelType
        marketingEvent{
            app{
                apiKey
                appStoreAppUrl
                appStoreDeveloperUrl
                description
                developerName
                developerType
                embedded
                features
                handle
                id
                installUrl
                isPostPurchaseAppInUse
                previouslyInstalled
                pricingDetails
                pricingDetailsSummary
                privacyPolicyUrl
                publicCategory
                published
                shopifyDeveloped
                title
                uninstallMessage
                webhookApiVersion
            }
            channelHandle
            description
            endedAt
            id
            legacyResourceId
            manageUrl
            marketingChannelType
            previewUrl
            remoteId
            scheduledToEndAt
            sourceAndMedium
            startedAt
            type
            utmCampaign
            utmMedium
            utmSource
        }
        parentActivityId
        parentRemoteId
        sourceAndMedium
        status
        statusBadgeTypeV2
        statusLabel
        statusTransitionedAt
        tactic
        targetStatus
        title
        updatedAt
        urlParameterValue
        utmParameters{
            campaign
            content
            medium
            source
            term
        }
    }
}