query marketLocalizableResources($marketId: ID!, $resourceType: MarketLocalizableResourceType!, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean){
    marketLocalizableResources(resourceType: $resourceType, first: $first, after: $after, last: $last, before: $before, reverse: $reverse){
        edges{
            cursor
            node{
                resourceId
            }
        }
        nodes{
            marketLocalizableContent{
                digest
                key
                value
            }
            marketLocalizations(marketId: $marketId){
                key
                outdated
                updatedAt
                value
            }
            resourceId
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}