query marketingEvents($first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $sortKey: MarketingEventSortKeys, $query: String){
    marketingEvents(first: $first, after: $after, last: $last, before: $before, reverse: $reverse, sortKey: $sortKey, query: $query){
        edges{
            cursor
            node{
                channelHandle
                description
                endedAt
                id
                legacyResourceId
                manageUrl
                marketingChannelType
                previewUrl
                remoteId
                scheduledToEndAt
                sourceAndMedium
                startedAt
                type
                utmCampaign
                utmMedium
                utmSource
            }
        }
        nodes{
            app{
                apiKey
                appStoreAppUrl
                appStoreDeveloperUrl
                description
                developerName
                developerType
                embedded
                features
                handle
                id
                installUrl
                isPostPurchaseAppInUse
                previouslyInstalled
                pricingDetails
                pricingDetailsSummary
                privacyPolicyUrl
                publicCategory
                published
                shopifyDeveloped
                title
                uninstallMessage
                webhookApiVersion
            }
            channelHandle
            description
            endedAt
            id
            legacyResourceId
            manageUrl
            marketingChannelType
            previewUrl
            remoteId
            scheduledToEndAt
            sourceAndMedium
            startedAt
            type
            utmCampaign
            utmMedium
            utmSource
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}