query productVendors($first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean){
    productVendors(first: $first, after: $after, last: $last, before: $before, reverse: $reverse){
        edges{
            cursor
            node
        }
        nodes
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}