query shopifyFunctions($apiType: String, $useCreationUi: Boolean, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean){
    shopifyFunctions(apiType: $apiType, useCreationUi: $useCreationUi, first: $first, after: $after, last: $last, before: $before, reverse: $reverse){
        edges{
            cursor
            node{
                apiType
                apiVersion
                appKey
                description
                id
                inputQuery
                title
                useCreationUi
            }
        }
        nodes{
            apiType
            apiVersion
            app{
                apiKey
                appStoreAppUrl
                appStoreDeveloperUrl
                description
                developerName
                developerType
                embedded
                features
                handle
                id
                installUrl
                isPostPurchaseAppInUse
                previouslyInstalled
                pricingDetails
                pricingDetailsSummary
                privacyPolicyUrl
                publicCategory
                published
                shopifyDeveloped
                title
                uninstallMessage
                webhookApiVersion
            }
            appBridge{
                createPath
                detailsPath
            }
            appKey
            description
            id
            inputQuery
            title
            useCreationUi
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}