query shopifyqlQuery($query: String!){
    shopifyqlQuery(query: $query){
        parseErrors
        tableData{
            columns{
                dataType
                displayName
                name
                subType
            }
            rows
        }
    }
}