query subscriptionBillingAttempts($audience: Audience, $notificationUsage: NotificationUsage, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $sortKey: SubscriptionBillingAttemptsSortKeys, $query: String){
    subscriptionBillingAttempts(first: $first, after: $after, last: $last, before: $before, reverse: $reverse, sortKey: $sortKey, query: $query){
        edges{
            cursor
            node{
                completedAt
                createdAt
                id
                idempotencyKey
                nextActionUrl
                originTime
                paymentGroupId
                paymentSessionId
                ready
                respectInventoryPolicy
            }
        }
        nodes{
            completedAt
            createdAt
            id
            idempotencyKey
            nextActionUrl
            order{
                billingAddressMatchesShippingAddress
                canMarkAsPaid
                canNotifyCustomer
                cancelReason
                cancelledAt
                capturable
                clientIp
                closed
                closedAt
                confirmationNumber
                confirmed
                createdAt
                currencyCode
                currentSubtotalLineItemsQuantity
                currentTotalWeight
                customerAcceptsMarketing
                customerLocale
                discountCode
                discountCodes
                displayFinancialStatus
                displayFulfillmentStatus
                dutiesIncluded
                edited
                email
                estimatedTaxes
                fulfillable
                fullyPaid
                hasTimelineComment
                id
                legacyResourceId
                merchantEditable
                merchantEditableErrors
                name
                note
                number
                paymentGatewayNames
                phone
                poNumber
                presentmentCurrencyCode
                processedAt
                productNetwork
                purchasingEntity{
                    __typename
                    ... on Customer {
                        canDelete
                        createdAt
                        dataSaleOptOut
                        displayName
                        email
                        firstName
                        hasTimelineComment
                        id
                        lastName
                        legacyResourceId
                        lifetimeDuration
                        locale
                        multipassIdentifier
                        note
                        numberOfOrders
                        phone
                        productSubscriberStatus
                        state
                        tags
                        taxExempt
                        taxExemptions
                        unsubscribeUrl
                        updatedAt
                        validEmailAddress
                        verifiedEmail
                    }
                }
                refundable
                registeredSourceUrl
                requiresShipping
                restockable
                returnStatus
                sourceIdentifier
                sourceName
                statusPageUrl(audience: $audience, notificationUsage: $notificationUsage)
                subtotalLineItemsQuantity
                tags
                taxExempt
                taxesIncluded
                test
                totalWeight
                unpaid
                updatedAt
            }
            originTime
            paymentGroupId
            paymentSessionId
            processingError{
                code
                message
            }
            ready
            respectInventoryPolicy
            subscriptionContract{
                appAdminUrl
                createdAt
                currencyCode
                deliveryMethod{
                    __typename
                }
                id
                lastBillingAttemptErrorType
                lastPaymentStatus
                nextBillingDate
                note
                revisionId
                status
                updatedAt
            }
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}