query subscriptionBillingCycles($contractId: ID!, $billingCyclesDateRangeSelector: SubscriptionBillingCyclesDateRangeSelector, $billingCyclesIndexRangeSelector: SubscriptionBillingCyclesIndexRangeSelector, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $sortKey: SubscriptionBillingCyclesSortKeys){
    subscriptionBillingCycles(contractId: $contractId, billingCyclesDateRangeSelector: $billingCyclesDateRangeSelector, billingCyclesIndexRangeSelector: $billingCyclesIndexRangeSelector, first: $first, after: $after, last: $last, before: $before, reverse: $reverse, sortKey: $sortKey){
        edges{
            cursor
            node{
                billingAttemptExpectedDate
                cycleEndAt
                cycleIndex
                cycleStartAt
                edited
                skipped
                status
            }
        }
        nodes{
            billingAttemptExpectedDate
            cycleEndAt
            cycleIndex
            cycleStartAt
            edited
            editedContract{
                appAdminUrl
                createdAt
                currencyCode
                deliveryMethod{
                    __typename
                }
                note
                updatedAt
            }
            skipped
            sourceContract{
                appAdminUrl
                createdAt
                currencyCode
                deliveryMethod{
                    __typename
                }
                id
                lastBillingAttemptErrorType
                lastPaymentStatus
                nextBillingDate
                note
                revisionId
                status
                updatedAt
            }
            status
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}