query subscriptionContracts($showRevoked: Boolean, $withName: Boolean, $withCompany: Boolean, $audience: Audience, $notificationUsage: NotificationUsage, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $sortKey: SubscriptionContractsSortKeys, $query: String){
    subscriptionContracts(first: $first, after: $after, last: $last, before: $before, reverse: $reverse, sortKey: $sortKey, query: $query){
        edges{
            cursor
            node{
                appAdminUrl
                createdAt
                currencyCode
                deliveryMethod{
                    __typename
                }
                id
                lastBillingAttemptErrorType
                lastPaymentStatus
                nextBillingDate
                note
                revisionId
                status
                updatedAt
            }
        }
        nodes{
            app{
                apiKey
                appStoreAppUrl
                appStoreDeveloperUrl
                description
                developerName
                developerType
                embedded
                features
                handle
                id
                installUrl
                isPostPurchaseAppInUse
                previouslyInstalled
                pricingDetails
                pricingDetailsSummary
                privacyPolicyUrl
                publicCategory
                published
                shopifyDeveloped
                title
                uninstallMessage
                webhookApiVersion
            }
            appAdminUrl
            billingPolicy{
                interval
                intervalCount
                maxCycles
                minCycles
            }
            createdAt
            currencyCode
            customAttributes{
                key
                value
            }
            customer{
                canDelete
                createdAt
                dataSaleOptOut
                displayName
                firstName
                id
                lastName
                legacyResourceId
                lifetimeDuration
                locale
                multipassIdentifier
                note
                numberOfOrders
                productSubscriberStatus
                state
                tags
                taxExempt
                taxExemptions
                updatedAt
                verifiedEmail
            }
            customerPaymentMethod(showRevoked: $showRevoked){
                id
                instrument{
                    __typename
                    ... on CustomerCreditCard {
                        brand
                        expiresSoon
                        expiryMonth
                        expiryYear
                        firstDigits
                        isRevocable
                        lastDigits
                        maskedNumber
                        name
                        source
                        virtualLastDigits
                    }
                    ... on CustomerPaypalBillingAgreement {
                        inactive
                        isRevocable
                        paypalAccountEmail
                    }
                    ... on CustomerShopPayAgreement {
                        expiresSoon
                        expiryMonth
                        expiryYear
                        inactive
                        isRevocable
                        lastDigits
                        maskedNumber
                        name
                    }
                }
                revokedAt
                revokedReason
            }
            deliveryMethod{
                __typename
                ... on SubscriptionDeliveryMethodLocalDelivery {
                    address{
                        address1
                        address2
                        city
                        company
                        coordinatesValidated
                        country
                        countryCodeV2
                        firstName
                        formatted(withName: $withName, withCompany: $withCompany)
                        formattedArea
                        id
                        lastName
                        latitude
                        longitude
                        name
                        phone
                        province
                        provinceCode
                        timeZone
                        validationResultSummary
                        zip
                    }
                    localDeliveryOption{
                        code
                        description
                        instructions
                        phone
                        presentmentTitle
                        title
                    }
                }
                ... on SubscriptionDeliveryMethodPickup {
                    pickupOption{
                        code
                        description
                        presentmentTitle
                        title
                    }
                }
                ... on SubscriptionDeliveryMethodShipping {
                    shippingOption{
                        code
                        description
                        presentmentTitle
                        title
                    }
                }
            }
            deliveryPolicy{
                interval
                intervalCount
            }
            deliveryPrice{
                amount
                currencyCode
            }
            id
            lastBillingAttemptErrorType
            lastPaymentStatus
            linesCount{
                count
                precision
            }
            nextBillingDate
            note
            originOrder{
                billingAddressMatchesShippingAddress
                canMarkAsPaid
                canNotifyCustomer
                cancelReason
                cancelledAt
                capturable
                clientIp
                closed
                closedAt
                confirmationNumber
                confirmed
                createdAt
                currencyCode
                currentSubtotalLineItemsQuantity
                currentTotalWeight
                customerAcceptsMarketing
                customerLocale
                discountCode
                discountCodes
                displayFinancialStatus
                displayFulfillmentStatus
                dutiesIncluded
                edited
                email
                estimatedTaxes
                fulfillable
                fullyPaid
                hasTimelineComment
                id
                legacyResourceId
                merchantEditable
                merchantEditableErrors
                name
                note
                number
                paymentGatewayNames
                phone
                poNumber
                presentmentCurrencyCode
                processedAt
                productNetwork
                purchasingEntity{
                    __typename
                    ... on Customer {
                        canDelete
                        createdAt
                        dataSaleOptOut
                        displayName
                        email
                        firstName
                        hasTimelineComment
                        id
                        lastName
                        legacyResourceId
                        lifetimeDuration
                        locale
                        multipassIdentifier
                        note
                        numberOfOrders
                        phone
                        productSubscriberStatus
                        state
                        tags
                        taxExempt
                        taxExemptions
                        unsubscribeUrl
                        updatedAt
                        validEmailAddress
                        verifiedEmail
                    }
                }
                refundable
                registeredSourceUrl
                requiresShipping
                restockable
                returnStatus
                sourceIdentifier
                sourceName
                statusPageUrl(audience: $audience, notificationUsage: $notificationUsage)
                subtotalLineItemsQuantity
                tags
                taxExempt
                taxesIncluded
                test
                totalWeight
                unpaid
                updatedAt
            }
            revisionId
            status
            updatedAt
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}