query subscriptionBillingCycleBulkResults($jobId: ID!, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean){
    subscriptionBillingCycleBulkResults(jobId: $jobId, first: $first, after: $after, last: $last, before: $before, reverse: $reverse){
        edges{
            cursor
            node{
                billingAttemptExpectedDate
                cycleEndAt
                cycleIndex
                cycleStartAt
                edited
                skipped
                status
            }
        }
        nodes{
            billingAttemptExpectedDate
            cycleEndAt
            cycleIndex
            cycleStartAt
            edited
            editedContract{
                appAdminUrl
                createdAt
                currencyCode
                deliveryMethod{
                    __typename
                }
                note
                updatedAt
            }
            skipped
            sourceContract{
                appAdminUrl
                createdAt
                currencyCode
                deliveryMethod{
                    __typename
                }
                id
                lastBillingAttemptErrorType
                lastPaymentStatus
                nextBillingDate
                note
                revisionId
                status
                updatedAt
            }
            status
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}