query validations($truncateAt: Int, $id: ID!, $onlyPublished: Boolean, $channelId: ID!, $publicationId: ID!, $audience: Audience, $notificationUsage: NotificationUsage, $truncateAt1: Int, $id1: ID!, $onlyPublished1: Boolean, $context: ContextualPublicationContext!, $channelId1: ID!, $publicationId1: ID!, $namespace: String, $key: String!, $first: Int, $after: String, $last: Int, $before: String, $reverse: Boolean, $sortKey: ValidationSortKeys){
    validations(first: $first, after: $after, last: $last, before: $before, reverse: $reverse, sortKey: $sortKey){
        edges{
            cursor
            node{
                blockOnFailure
                enabled
                id
                title
            }
        }
        nodes{
            blockOnFailure
            enabled
            errorHistory{
                errorsFirstOccurredAt
                firstOccurredAt
                hasBeenSharedSinceLastError
                hasSharedRecentErrors
            }
            id
            metafield(namespace: $namespace, key: $key){
                compareDigest
                createdAt
                id
                jsonValue
                key
                legacyResourceId
                namespace
                ownerType
                reference{
                    __typename
                    ... on Article {
                        body
                        createdAt
                        defaultCursor
                        handle
                        id
                        isPublished
                        publishedAt
                        summary
                        tags
                        templateSuffix
                        title
                        updatedAt
                    }
                    ... on Collection {
                        description(truncateAt: $truncateAt)
                        descriptionHtml
                        handle
                        hasProduct(id: $id)
                        id
                        legacyResourceId
                        publicationCount(onlyPublished: $onlyPublished)
                        publishedOnChannel(channelId: $channelId)
                        publishedOnCurrentChannel
                        publishedOnCurrentPublication
                        publishedOnPublication(publicationId: $publicationId)
                        sortOrder
                        storefrontId
                        templateSuffix
                        title
                        updatedAt
                    }
                    ... on Company {
                        contactCount
                        createdAt
                        customerSince
                        defaultCursor
                        externalId
                        hasTimelineComment
                        id
                        lifetimeDuration
                        name
                        note
                        updatedAt
                    }
                    ... on Customer {
                        canDelete
                        createdAt
                        dataSaleOptOut
                        displayName
                        email
                        firstName
                        hasTimelineComment
                        id
                        lastName
                        legacyResourceId
                        lifetimeDuration
                        locale
                        multipassIdentifier
                        note
                        numberOfOrders
                        phone
                        productSubscriberStatus
                        state
                        tags
                        taxExempt
                        taxExemptions
                        unsubscribeUrl
                        updatedAt
                        validEmailAddress
                        verifiedEmail
                    }
                    ... on GenericFile {
                        alt
                        createdAt
                        fileStatus
                        id
                        mimeType
                        originalFileSize
                        updatedAt
                        url
                    }
                    ... on MediaImage {
                        alt
                        createdAt
                        fileStatus
                        id
                        mediaContentType
                        mimeType
                        status
                        updatedAt
                    }
                    ... on Metaobject {
                        displayName
                        handle
                        id
                        type
                        updatedAt
                    }
                    ... on Model3d {
                        alt
                        createdAt
                        fileStatus
                        filename
                        id
                        mediaContentType
                        status
                        updatedAt
                    }
                    ... on Order {
                        billingAddressMatchesShippingAddress
                        canMarkAsPaid
                        canNotifyCustomer
                        cancelReason
                        cancelledAt
                        capturable
                        cartDiscountAmount
                        clientIp
                        closed
                        closedAt
                        confirmationNumber
                        confirmed
                        createdAt
                        currencyCode
                        currentSubtotalLineItemsQuantity
                        currentTotalWeight
                        customerAcceptsMarketing
                        customerLocale
                        discountCode
                        discountCodes
                        displayFinancialStatus
                        displayFulfillmentStatus
                        dutiesIncluded
                        edited
                        email
                        estimatedTaxes
                        fulfillable
                        fullyPaid
                        hasTimelineComment
                        id
                        landingPageDisplayText
                        landingPageUrl
                        legacyResourceId
                        merchantEditable
                        merchantEditableErrors
                        name
                        netPayment
                        note
                        number
                        paymentGatewayNames
                        phone
                        poNumber
                        presentmentCurrencyCode
                        processedAt
                        productNetwork
                        purchasingEntity{
                            __typename
                            ... on Customer {
                                canDelete
                                createdAt
                                dataSaleOptOut
                                displayName
                                email
                                firstName
                                hasTimelineComment
                                id
                                lastName
                                legacyResourceId
                                lifetimeDuration
                                locale
                                multipassIdentifier
                                note
                                numberOfOrders
                                phone
                                productSubscriberStatus
                                state
                                tags
                                taxExempt
                                taxExemptions
                                unsubscribeUrl
                                updatedAt
                                validEmailAddress
                                verifiedEmail
                            }
                        }
                        referralCode
                        referrerDisplayText
                        referrerUrl
                        refundable
                        registeredSourceUrl
                        requiresShipping
                        restockable
                        returnStatus
                        riskLevel
                        sourceIdentifier
                        sourceName
                        statusPageUrl(audience: $audience, notificationUsage: $notificationUsage)
                        subtotalLineItemsQuantity
                        subtotalPrice
                        tags
                        taxExempt
                        taxesIncluded
                        test
                        totalCapturable
                        totalDiscounts
                        totalPrice
                        totalReceived
                        totalRefunded
                        totalShippingPrice
                        totalTax
                        totalWeight
                        unpaid
                        updatedAt
                    }
                    ... on Page {
                        body
                        bodySummary
                        createdAt
                        defaultCursor
                        handle
                        id
                        isPublished
                        publishedAt
                        templateSuffix
                        title
                        updatedAt
                    }
                    ... on Product {
                        bodyHtml
                        combinedListingRole
                        createdAt
                        customProductType
                        defaultCursor
                        description(truncateAt: $truncateAt1)
                        descriptionHtml
                        descriptionPlainSummary
                        giftCardTemplateSuffix
                        handle
                        hasOnlyDefaultVariant
                        hasOutOfStockVariants
                        hasVariantsThatRequiresComponents
                        id
                        inCollection(id: $id1)
                        isGiftCard
                        legacyResourceId
                        onlineStorePreviewUrl
                        onlineStoreUrl
                        productType
                        publicationCount(onlyPublished: $onlyPublished1)
                        publishedAt
                        publishedInContext(context: $context)
                        publishedOnChannel(channelId: $channelId1)
                        publishedOnCurrentChannel
                        publishedOnCurrentPublication
                        publishedOnPublication(publicationId: $publicationId1)
                        requiresSellingPlan
                        sellingPlanGroupCount
                        status
                        storefrontId
                        tags
                        templateSuffix
                        title
                        totalInventory
                        totalVariants
                        tracksInventory
                        updatedAt
                        vendor
                    }
                    ... on ProductVariant {
                        availableForSale
                        barcode
                        compareAtPrice
                        createdAt
                        defaultCursor
                        displayName
                        id
                        inventoryPolicy
                        inventoryQuantity
                        legacyResourceId
                        position
                        price
                        requiresComponents
                        sellableOnlineQuantity
                        sellingPlanGroupCount
                        showUnitPrice
                        sku
                        storefrontId
                        taxCode
                        taxable
                        title
                        updatedAt
                    }
                    ... on TaxonomyValue {
                        id
                        name
                    }
                    ... on Video {
                        alt
                        createdAt
                        duration
                        fileStatus
                        filename
                        id
                        mediaContentType
                        status
                        updatedAt
                    }
                }
                type
                updatedAt
                value
            }
            shopifyFunction{
                apiType
                apiVersion
                appKey
                description
                id
                inputQuery
                title
                useCreationUi
            }
            title
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}